SELECT ASCII(First_Name) FROM Customer;
SELECT char_length(First_Name) From Customer Where Customer_ID = 122;
SELECT find_in_set("H", First_Name) From Customer Where Customer_ID = 122;
SELECT LCASE(First_Name) From Customer;
SELECT UCASE(First_Name) From Customer;
SELECT UPPER(First_Name) From Customer;
SELECT LOWER(First_Name) From Customer;
SELECT LEFT(First_Name, 3) From Customer;
SELECT RIGHT(First_Name, 3) From Customer;
SELECT LTRIM(Second_Name) From Customer;
SELECT RTRIM(First_Name) From Customer;
SELECT REPEAT(Customer_ID, 3) From Customer;
SELECT REPLACE(Customer_ID, "1", "2") From Customer Where Customer_ID = 122;
SELECT REVERSE(Customer_ID) From Customer;
SELECT SPACE(10);
SELECT STRCMP(First_Name, Second_Name) From Customer;
SELECT SUBSTR(First_Name, 1, 3) From Customer;
SELECT SUBSTRING(First_Name, 1, 3) From Customer;
SELECT SUBSTRING_INDEX(First_Name, "H", 1) From Customer;
SELECT CONCAT(First_Name, Second_Name) From Customer;